### ISSUE TITLE
Python analyzer does not provide hints

### ISSUE THREAD

**Issue by edigaryev** [cirruslabs/intellij-starlark#1]
The following `.cirrus.star`:

```
def main(ctx):
    a = []
    a.
      ^ No suggestions 🤷
    return []
```

..doesn't seem to analyze `a` variable similarly what can be expected of PyCharm:

![Screenshot 2021-05-07 at 18 36 03](https://user-images.githubusercontent.com/85709/117473923-23ab8b00-af63-11eb-8761-90a83a497f51.png)

**Comment by fkorotkov** [comment]
Fixed by #2 and will be shortly available in `1.3` version.
